bg-app
bg-footer
bg-header
bg-header-hover
bg-nav-bar
bg-nav-bar-hover
bg-nav-option
bg-nav-option-hover
bg-nav-profile-header
bg-toolbar
bg-button-brand
bg-button-brand-hover
bg-button-default
bg-button-default-hover
bg-button-muted
bg-button-muted-hover
bg-table-header
bg-table-row-1
bg-table-row-2
bg-table-row-muted
bg-panel
bg-modal
bg-modal-blur
bg-modal-header
bg-modal-footer
bg-input
bg-input-brand
bg-input-muted
bg-success
bg-error
bg-warning
bg-info
bg-debug
bg-brand-lightest
bg-brand-lighter
bg-brand-light
bg-brand
bg-brand-dark
bg-brand-darker
bg-brand-darkest
border-transparent
border-default
border-header
border-footer
border-nav-divider
border-nav
border-toolbar
border-nav-avatar
border-button-brand
border-button-brand-hover
border-button-default
border-button-default-hover
border-button-muted
border-button-muted-hover
border-table
border-table-divider
border-panel
border-panel-divider
border-modal
border-input
border-input-focus
border-success
border-error
border-warning
border-info
border-debug
placeholder-input
ring-brand
ring-offset-input
text-default
text-muted
text-link
text-link-hover
text-footer
text-header
text-header-muted
text-header-link
text-header-link-hover
text-nav-bar
text-nav-bar-hover
text-nav-option
text-nav-option-hover
text-nav-icon
text-nav-icon-hover
text-nav-profile
text-nav-muted
text-toolbar
text-button-brand
text-button-brand-hover
text-button-brand-icon
text-button-brand-icon-hover
text-button-default
text-button-default-hover
text-button-default-icon
text-button-default-icon-hover
text-button-muted
text-button-muted-hover
text-button-muted-icon
text-button-muted-icon-hover
text-table-header
text-table-header-hover
text-table-row
text-table-row-muted
text-panel
text-panel-header
text-input
text-input-muted
text-modal
text-modal-muted
text-success
text-error
text-warning
text-info
text-debug
text-brand-lightest
text-brand-lighter
text-brand-light
text-brand
text-brand-dark
text-brand-darker
text-brand-darkest
